name: Deploy

on:
  push:
    branches:
      - franco-develop

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using SSH and Docker Compose
        shell: bash
        run: |
          ssh -o StrictHostKeyChecking=no franco@192.168.30.11 << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker-compose pull
            docker-compose up -d
          EOF